title: Hannah Skye Smith
description: Planning & Design
baseurl: ""
url: https://www.hannahskyesmith.com

remote_theme: piazzai/cvless

# site settings
taglong: Urban Planning and Design 
tagshort: Urban Planning and Design

# author settings
author:
  name: Hannah Skye Smith
  email: hannahskyesmith@gmail.com
photo: assets/files/photo.jpg
address: Salt Lake City, UT
phone: +1 801 971 1925

# social media links
social:
  
 

  linkedin: hannahskyesmith

  

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
